### ISSUE TITLE
Configuration Files for MS COCO

### ISSUE THREAD

**Issue by HaitaoWen** [YuyangSunshine/ABR_IOD#3]
Hello! Thanks for your outstanding work! I am trying to reproduce the results on MS COCO. Could you please provide the corresponding configuration files?

**Comment by YuyangSunshine** [comment]
Thanks for your attention.
I will release the detailed configuration files for COCO.

**Comment by HaitaoWen** [comment]
Thank you very much!

**Comment by order-a-lemonade** [comment]
@YuyangSunshine  dear author, may i ask when will you release the configuration files for COCO? thanks.

**Comment by kelvin320** [comment]
@YuyangSunshine, Thank you for your impressive work! I am attempting to replicate the results on MS COCO. Could you kindly provide the relevant configuration files?

**Comment by YuyangSunshine** [comment]
Hi, all

Here are some configuration settings of COCO:

task 70-10 （mem：10k；iteration 35k；lr 0.002；alpha 0.1； beta 0.1；lambda 1）

task 40-40 （mem：5k；iteration 90k；lr 0.001；alpha 0.1； beta 0.1；lambda 1）

Thanks for your attention!
