### ISSUE TITLE
Questions about ABR loss

### ISSUE THREAD

**Issue by suntofu35** [YuyangSunshine/ABR_IOD#4]
Thank you for your great work and release of source code!

I have some questions about ABR loss.

In the paper, you say that using unbiased losses directly is not feasible because the ABR input image contains many annotations about previous objects.
However in the code, it seems that roi-head classification loss looks the same as MMA's unbiased classification loss.
And, as shown in line 102 of train_incremental.py, soften_proposal is set to None, so MMA's unbiased distillation loss is used for roi-distillation loss.

I wonder if it is right to use these losses as the loss to train ABR.

**Comment by zhongjian1999** [comment]
> Thank you for your great work and release of source code!
> 
> I have some questions about ABR loss.
> 
> In the paper, you say that using unbiased losses directly is not feasible because the ABR input image contains many annotations about previous objects. However in the code, it seems that roi-head classification loss looks the same as MMA's unbiased classification loss. And, as shown in line 102 of train_incremental.py, soften_proposal is set to None, so MMA's unbiased distillation loss is used for roi-distillation loss.
> 
> I wonder if it is right to use these losses as the loss to train ABR.

I have the same question, waiting for author's explain.
Did you get the same results as reported in paper without change the code?

**Comment by YuyangSunshine** [comment]
Hi @suntofu35，

Thank you for your interest in our work!

The final version of Inclusive distillation loss is:
![image](https://github.com/YuyangSunshine/ABR_IOD/assets/40997704/0e5e7129-880c-4b53-904e-1dbffd2aae9b)

We use the same code of distillation loss with MMA, but the Augmented Box Replay participates in the entire distillation process, retaining the knowledge of the original model and old categories and better helping the new model not to forget.

BTW, @zhongjian1999. If there's something wrong with the results you got, can I take a look at your environment configuration or something?

I hope this clarifies your doubts.

Yuyang
​
