### ISSUE TITLE
Experiments on other networks

### ISSUE THREAD

**Issue by ZS-YANG** [YuyangSunshine/ABR_IOD#5]
Thank you for your great work and release of source code! I have some questions.

Have you experimented on other networks? And can this method be used in single-stage object detection networks such as Yolo?

Looking forward to your reply, thx.

**Comment by YuyangSunshine** [comment]
Hi Yang,

Thanks for your attention.

It's a good suggestion to expand our method to other baselines.
But I didn't try to apply our method to the single-stage object detection networks in the current version.

If you are interested, you can try to use the ABR in the single-stage models.

Best.

**Comment by ZS-YANG** [comment]
thx. 🤞🤞🤞
